import React from 'react';

const data = {
  products: [
    {
      name: 'Slim shirts',
      slug: 'slim-shirts',
      category: 'shirts',
      image: '/images/shirt1.jpg',
      price: 'Rs.120',
      brand: 'Polo',
      rating: 4.5,
      numOfReviews: 10,
      countInStock: 25,
      description: 'Slim looking shirts',
    },
    {
      name: 'Fit shirts',
      slug: 'fit-shirts',
      category: 'shirts',
      image: '/images/shirt2.jpg',
      price: 'Rs.220',
      brand: 'Van Huesen',
      rating: 3.5,
      numOfReviews: 110,
      countInStock: 253,
      description: 'Fit looking shirts',
    },
    {
      name: 'Casual shirts',
      slug: 'casual-shirts',
      category: 'shirts',
      image: '/images/shirt3.jpg',
      price: 'Rs.620',
      brand: 'Indian Tribe',
      rating: 3.9,
      numOfReviews: 410,
      countInStock: 54,
      description: 'Casual shirts for outdoor ',
    },
    {
      name: 'Cargo pants',
      slug: 'cargo-pants',
      category: 'pants',
      image: '/images/pant1.jpg',
      price: 'Rs.430',
      brand: 'Polo',
      rating: 4.7,
      numOfReviews: 1120,
      countInStock: 251,
      description: 'Pants with a lot of pockets',
    },
    {
      name: 'Formal pants',
      slug: 'formal-pants',
      category: 'pants',
      image: '/images/pant2.jpg',
      price: 'Rs.1000',
      brand: 'LV',
      rating: 5,
      numOfReviews: 1110,
      countInStock: 258,
      description: 'Pants for formal events and functions',
    },
  ],
};

export default data;
